const movies = [
  {id:'1', title: 'Friday The 13th', rating: 3,duration: 90,releaseDate: 1980, genre: 'Horror', description: 'Produced and directed by Sean S. Cunningham, written by Victor Miller, and starring Betsy Palmer, Adrienne King, Harry Crosby, Laurie Bartram, Mark Nelson, Jeannine Taylor, Robbi Morgan, and Kevin Bacon. Its plot follows a group of teenage camp counselors who are murdered one by one by an unknown killer while attempting to re-open an abandoned summer camp.'},
  {id:'2', title: 'Titanic', rating: 4.6,duration: 160,releaseDate: 1997, genre: 'Drama', description: 'Directed, written, co-produced, and co-edited by James Cameron. Incorporating both historical and fictionalized aspects, it is based on accounts of the sinking of the RMS Titanic, and stars Leonardo DiCaprio and Kate Winslet as members of different social classes who fall in love aboard the ship during its ill-fated maiden voyage.'},
  {id:'3', title: 'Dumb & Dumber', rating: 3.4,duration: 80,releaseDate: 1994, genre: 'Comedy', description: 'Directed by Peter Farrelly, who co-wrote the screenplay with Bobby Farrelly and Bennett Yellin. Starring Jim Carrey and Jeff Daniels, it tells the story of Lloyd Christmas (Carrey) and Harry Dunne (Daniels), two dumb but well-meaning friends from Providence, Rhode Island, who set out on a cross-country trip to Aspen, Colorado, to return a briefcase full of money to its owner, thinking it was abandoned as a mistake but was actually left as ransom money.'},
  {id:'4', title: 'Avengers End Game', rating: 4,duration: 150,releaseDate: 2019, genre: 'Adventure', description: 'based on the Marvel Comics superhero team the Avengers, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU). The film was directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely.'},
  {id:'5', title: 'IT', rating: 3.8,duration: 120,releaseDate: 2017, genre: 'Horror', description: 'based on Stephen King\'s 1986 novel of the same name. Produced by New Line Cinema, KatzSmith Productions, Lin Pictures, Vertigo Entertainment, and distributed by Warner Bros. It is the first film in the It film series as well as being the second adaptation following Tommy Lee Wallace\'s 1990 miniseries. The film tells the story of seven children in Derry, Maine, who are terrorized by the eponymous being, only to face their own personal demons in the process.'},
  {id:'6', title: 'Toy Story', rating: 4,duration: 90,releaseDate: 1995, genre: 'Comedy', description: 'Taking place in a world where anthropomorphic toys come to life when humans are not present, the plot focuses on the relationship between an old-fashioned pull-string cowboy doll named Woody and an astronaut action figure, Buzz Lightyear, as they evolve from rivals competing for the affections of their owner Andy Davis, to friends who work together to be reunited with him after being separated from him.'}
];

export default movies;